# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'CocoaPodExample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CocoaPodExample
  pod 'ViewDeck'

  target 'CocoaPodExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocoaPodExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
